let place: Array <string> = ['Makkah', 'Madina', 'Tokyo', 'Paris', 'London']
console.log("Original Order")
console.log(place)
console.log("\t Alphabetical Order \n")
console.log([...place].sort())
console.log("\t Showing that array is still in its original order. \n")
console.log(place)
console.log("\t Reverse Alphabetical Order \n")
console.log([...place].sort().reverse())
console.log("\t Showing that array is still in its original order. \n")
console.log(place)
console.log("\t Reverse order \n")
place.reverse()
console.log(place)
console.log("\t Back to original order \n")
place.reverse()
console.log(place)
console.log("\t Change to Alphabetical order \n")
place.sort()
console.log(place)
console.log("\t Change to Reverse Alphabetical order \n")
place.sort().reverse()
console.log(place)