console.log("_".repeat(80))
console.log(6 + 2)
console.log("_".repeat(80))
console.log(13 - 5)
console.log("_".repeat(80))
console.log(2 * 4)
console.log("_".repeat(80))
console.log(24 / 3)
console.log("_".repeat(80))